xunholy/k8s-gitops

- policies/CIS.1.2.10.rego
- policies/CIS.1.2.10_test.rego
- policies/CIS.1.2.11.rego
- policies/CIS.1.2.11_test.rego
- policies/CIS.1.2.12.rego
- policies/CIS.1.2.12_test.rego
- policies/CIS.1.2.13.rego
- policies/CIS.1.2.13_test.rego
- policies/CIS.1.2.14.rego
- policies/CIS.1.2.14_test.rego
- policies/CIS.1.2.15.rego
- policies/CIS.1.2.15_test.rego
- policies/CIS.1.2.16.rego
- policies/CIS.1.2.16_test.rego
- policies/CIS.1.2.17.rego
- policies/CIS.1.2.17_test.rego
- policies/lib/kubernetes.rego
Creating CIS benchmark items for 1.2.10 to 1.2.17 in rego policies.
> adding CIS Benchmark controls for 1.2.10-1.2.17

- policies/CIS.1.2.1.rego
- policies/CIS.1.2.10.rego
- policies/CIS.1.2.10_test.rego
- policies/CIS.1.2.11.rego
- policies/CIS.1.2.11_test.rego
- policies/CIS.1.2.12.rego
- policies/CIS.1.2.12_test.rego
- policies/CIS.1.2.13.rego
- policies/CIS.1.2.13_test.rego
- policies/CIS.1.2.14.rego
- policies/CIS.1.2.14_test.rego
- policies/CIS.1.2.15.rego
- policies/CIS.1.2.15_test.rego
- policies/CIS.1.2.16.rego
- policies/CIS.1.2.16_test.rego
- policies/CIS.1.2.17.rego
- policies/CIS.1.2.17_test.rego
- policies/CIS.1.2.1_test.rego
- policies/lib/kubernetes.rego
Signed-off-by: hus5 <siyuan.hu@anz.com>
> Feature/cis benchmarks 1.2.1

- policies/CIS.1.4.1.rego
- policies/CIS.1.4.1_test.rego
Adding controls for CIS Benchmark for 5.4.1
Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #29
> adding CIS Benchmark controls for 5.4.1

- policies/CIS.1.2.10_test.rego
- policies/CIS.1.2.12_test.rego
- policies/CIS.1.2.14_test.rego
- policies/CIS.1.2.15_test.rego
- policies/CIS.1.2.16_test.rego
- policies/CIS.1.2.1_test.rego
- policies/CIS.2.1.rego
- policies/CIS.2.1_test.rego
- policies/CIS.2.2.rego
- policies/CIS.2.2_test.rego
- policies/CIS.2.3.rego
- policies/CIS.2.3_test.rego
- policies/CIS.2.4.rego
- policies/CIS.2.4_test.rego
- policies/CIS.2.5.rego
- policies/CIS.2.5_test.rego
- policies/CIS.2.6.rego
- policies/CIS.2.6_test.rego
- policies/CIS.5.5.1_test.rego
- policies/lib/kubernetes.rego
Adding the security controls for ETCD 2.x 
Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #21 
> adding etcd cis 2.x controls

- policies/CIS.5.1.3.rego
- policies/CIS.5.1.3_test.rego
- policies/lib/kubernetes.rego
Signed-off-by: Saurabh Pandit <saurabhpandit@users.noreply.github.com>
Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #26 
> CIS Benchmark policy 5.1.3

- policies/CIS.1.2.2.rego
- policies/CIS.1.2.2_test.rego
- policies/CIS.1.2.3.rego
- policies/CIS.1.2.3_test.rego
- policies/CIS.1.2.4.rego
- policies/CIS.1.2.4_test.rego
Signed-off-by: hus5 <siyuan.hu@anz.com>
> cis1.2.2-1.2.4

- policies/CIS.5.1.5.rego
- policies/CIS.5.1.5_test.rego
Signed-off-by: Saurabh Pandit <saurabhpandit@users.noreply.github.com>
Implementing policy 5.1.5
> CIS Kubernetes Policy 5.1.5

- policies/CIS.5.2.1.rego
- policies/CIS.5.2.1_test.rego
- policies/CIS.5.2.2.rego
- policies/CIS.5.2.2_test.rego
- policies/CIS.5.2.3.rego
- policies/CIS.5.2.3_test.rego
- policies/CIS.5.2.4.rego
- policies/CIS.5.2.4_test.rego
- policies/CIS.5.2.5.rego
- policies/CIS.5.2.5_test.rego
Adding controls:
- 5.2.1
- 5.2.2
- 5.2.3
- 5.2.4
- 5.2.5
> adding CIS controls 5.2.x

- policies/CIS.1.2.10_test.rego
- policies/CIS.1.2.1_test.rego
- policies/CIS.1.2.2_test.rego
- policies/CIS.1.2.3_test.rego
- policies/CIS.1.2.4_test.rego
- policies/CIS.1.3.2.rego
- policies/CIS.1.3.2_test.rego
- policies/CIS.1.3.7.rego
- policies/CIS.1.3.7_test.rego
- policies/CIS.1.4.2.rego
- policies/CIS.1.4.2_test.rego
- policies/CIS.5.4.1.rego
- policies/CIS.5.4.1_test.rego
- policies/lib/kubernetes.rego
> adding CIS controls 1.x.x

- policies/CIS.1.3.2_test.rego
- policies/CIS.1.3.7_test.rego
- policies/CIS.1.4.1_test.rego
- policies/CIS.1.4.2_test.rego
- policies/lib/kubernetes.rego
Rename label component for kube-scheduler and kube-controller-manager
> rename label component

- policies/CIS.5.1.2.rego
- policies/CIS.5.1.2_test.rego
Signed-off-by: Saurabh Pandit <saurabhpandit@users.noreply.github.com>
> CIS Kubernetes Benchmark policy 5.1.2

- .github/workflows/build.yml
- anthos/namespaces/flux/namespace.yaml
Adding nomos to validation configuration expectation of Config Sync
> Integrate nomos into workflow

- .github/workflows/build.yml
Adding kube-score to the workflow to validate resources
> Integrate kube-score into workflow

- namespaces/storage/openebs/openebs.yaml
Update OpenEBS helm chart path and images being used within the cluster to most recent helm versions.
> updating helm-chart for openebs to use latest versions

- .github/workflows/build.yml
- [x ] Security
- [x ] Test and/or Release
Modified the hrval action to allow for passing an action, either 'kubeval' for standard hval behavior or 'conftest' to run conftest over the templated yamls. Inspired by edshelton/hrval and updated with changes from hrval v3.3.0.
> conftest helm charts

- .github/FUNDING.yml
> adding FUNDING support

- .github/FUNDING.yml
- README.md
> Update README with sponsors

- README.md
> adding BACKERS

- .github/PULL_REQUEST_TEMPLATE.md
- .github/release-drafter.yml
- .github/workflows/builder-image.yml
- .github/workflows/release-drafter.yml
- .github/workflows/sealed-secrets.yml
- build/docker/Dockerfile
Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #122 
> update workflows, create basic release drafter, update Dockerfile

- .gitmodules
Update the repository URL to the new refactored name.
Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #49
> Update repo path in git submodule

- .github/PULL_REQUEST_TEMPLATE.md
- namespaces/istio-system/istio/peerauthentication.yaml
- namespaces/istio-system/istio/serviceentry.yaml
add istio strict mTLS with a default `PeerAuthentication` resource in the `istio-system` namespace and configure service entries  for external cluster resources to googleapis used by velero
> add istio strict mTLS and configure service entries 

- .github/workflows/builder-image.yml
- .pre-commit-config.yaml
- cluster/actions-runner-system/secret.encrypted.yaml
- cluster/flux-system/webhook-receiver/secret.encrypted.yaml
- cluster/network/cert-manager/secret.encrypted.yaml
- cluster/network/dex/secret.encrypted.yaml
- cluster/network/external-dns/secret.encrypted.yaml
- cluster/network/oauth2-proxy/secret.encrypted.yaml
- cluster/observability/thanos/secret.encrypted.yaml
- infrastructure/gcp/README.md
- infrastructure/gcp/install.sh
Fix a bug where the previous yaml linter wasn't consistent with yamllint.
Enable local pre-commit and execute across all local files
> update pre-commit yamllint and lint all files

- cluster/observability/kube-prometheus-stack/kube-prometheus-stack.yaml
Adding the cloudflare grafana app - installation steps can be found here https://support.cloudflare.com/hc/en-us/articles/115002722267-Install-the-Cloudflare-Grafana-Plugin 
Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): #130 
> adding cloudflared plugin

- COMMUNITY.md
Creating the initial community document to help the community collaborate, and learn from each other's examples.
@onedr0p @carpenike @billimek I'd love to add you guys with links to your repositories if you're happy to do so.
> there is a lot of awesome engineers who have helped inspire this project.
You guys particularly (and a few others) have helped a lot and I wanted to express my gratitude to each of you.
> Add initial community document

- COMMUNITY.md
Just adding my unorganized repo to your list. The more the merrier!
> Added my repo with a quick description

- COMMUNITY.md
Adding reference to my own repository, now that I've migrated to GitHub.
> add reference to my cluster repo

- cluster/network/dex/dex.yaml
Updating DEX version to latest image and pull image from GHCR
> update dex version v2.26.0

- COMMUNITY.md
Signed-off-by: Curtis John <admin@curtisrayjohn.com>
Add crutonjohn to community repos section
> adding crutonjohn to community

- COMMUNITY.md
Please provide a description of what this PR is for.
> adding carpenike

- COMMUNITY.md
Added my repository referencing infra/gitops as code.
Signed-off-by: anthr76 <hello@anthonyrabbito.com>
This is just a documentation change so checklist can be N/A.
> Added my repository to community.

- COMMUNITY.md
Signed-off-by: Russell Hall <owner@russellhall.co.uk>
Please provide a description of what this PR is for.
> Add rust84 to community

- COMMUNITY.md
Adding @billimek to the COMMUNITY.md table of examples
> adding billimek to COMMUNITY.md

- COMMUNITY.md
Please provide a description of what this PR is for.
> Add bjw-s repo

- cluster/flux-system/helm-chart-repositories/banzaicloud-charts.yaml
- cluster/flux-system/helm-chart-repositories/bitnami-charts.yaml
- cluster/flux-system/helm-chart-repositories/gatekeeper-charts.yaml
- cluster/flux-system/helm-chart-repositories/grafana-loki.yaml
- cluster/flux-system/helm-chart-repositories/jetstack-charts.yaml
- cluster/flux-system/helm-chart-repositories/k8s-at-home-charts.yaml
- cluster/flux-system/helm-chart-repositories/kubernetes-sigs-charts.yaml
- cluster/flux-system/helm-chart-repositories/kubernetes-stable-charts.yaml
- cluster/flux-system/helm-chart-repositories/litmuschaos-charts.yaml
- cluster/flux-system/helm-chart-repositories/openebs-charts.yaml
- cluster/flux-system/helm-chart-repositories/openfaas-charts.yaml
- cluster/flux-system/helm-chart-repositories/prometheus-community-charts.yaml
- cluster/flux-system/helm-chart-repositories/vmware-charts.yaml
- cluster/flux-system/helm-chart-repositories/weaveworks-kured-charts.yaml
- cluster/kube-system/descheduler/descheduler.yaml
- cluster/observability/kube-prometheus-stack/kube-prometheus-stack.yaml
Adding descheduler to better manage resources across nodes and distribute load.
Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #171 
> Add descheduler with target thresholds

- cluster/observability/kube-prometheus-stack/kube-prometheus-stack.yaml
Use upstream multi-arch kube-state-metrics image
> update kube-state-metrics to use upstream image

- infrastructure/gcp/sops.tf
Add TF to grant users the ability to encrypt/decrypt secrets within the project.
> Add explicit list of users to grant GCP project permissions

- .github/workflows/merge.yml
- cilium/install/README.md
Testing PR for auto-merge and bumping cilium to 1.9.1
> updating version to use 1.9.1

- .github/workflows/docs.yaml
- docs/README.md
- docs/_static/custom.css
- docs/index.md
- mkdocs.yml
Add default mkdocs configuration
- [] All commits contain a well-written commit description including a title, description, and a Fixes: #XXX line if the commit addresses a particular GitHub issue.
> feat: adding base mkdocs configuration

- k8s/namespaces/base/flux-system/helm-chart-repositories/node-feature-discovery-chart.yaml
- k8s/namespaces/base/network/node-feature-discovery/helmrelease.yaml
Pending PR to fix the indentation issue on the worker config.
> feat: adding new upstream maintained nfd chart

- .github/workflows/e2e.yml
- docs/README.md
- k8s/core/base/applications/istio-operator/kustomization.yaml
Update istio-operator to also deploy CRDs
Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #371 
> fix: add istio crds to kustomization

- .github/workflows/e2e.yml
- docs/README.md
- k8s/core/base/applications/istio-operator/kustomization.yaml
- k8s/core/base/applications/istio/istio-1.9.2.yaml
- k8s/core/base/crds/cert-manager/kustomization.yaml
- k8s/namespaces/base/network/cert-manager/helmrelease.yaml
> Update cert-manager v1.3.0

- k8s/namespaces/base/flux-system/helm-chart-repositories/stakater-charts.yaml
- k8s/namespaces/base/kube-system/reloader/helmrelease.yaml
- k8s/namespaces/base/kube-system/reloader/kustomization.yaml
- k8s/namespaces/overlays/production-gke/kustomization.yaml
- k8s/namespaces/overlays/production/kustomization.yaml
- k8s/namespaces/overlays/staging/kustomization.yaml
Add reloader to be able to restart pods when configmaps and/or secrets are updated in the cluster.
- x] All commits contain a well-written commit description including a title, description, and a Fixes: #XXX line if the commit addresses a particular GitHub issue.
> feat: adding reloader helm chart

- .github/renovate.json5
- .github/renovate/autoMerge.json5
- .github/renovate/commitMessage.json5
- .github/renovate/labels.json5
- .github/renovate/semanticCommits.json5
> feat: update renovate
